#应用服务配置
server:
  port: 8081
  context-path: /
debug: true

#日志配置
logging:
  level:
    root: debug
    tk:
      mybatis:
        springboot:
          mapper: trace
  config: classpath:logback.xml

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guanghuan3?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  mapper-locations: classpath:com/guanghuan3/customer/**/*Mapper.xml
  type-aliases-package: com.zwb.pojo

# 通用mapper配置
mapper:
  mappers: com.zwb.mybatis.BusiMapper,com.zwb.mybatis.InfoMapper
  not-empty: false
  identity: MYSQL

#分页插件配置
pagehelper:
  reasonable: true
  params: count=countSql
  helper-dialect: mysql

#api-list:
#  get:
#    /customer: getCustomerExecutor
#    /country: getCountryExecutor
#    /country/list: getCountryListExecutor
#  post:
#    /customer: addCustomerExecutor
#    /customer/details: addCustomerDetailsExecutor